spring.application.name=booking-service
server.port=8083
 
spring.data.mongodb.uri=mongodb+srv://harrishshermon_db_user:OxYLP13p2PvogEPj@bookingservice.xhqd1si.mongodb.net/BookingService?retryWrites=true&w=majority
spring.jackson.serialization.write-dates-as-timestamps=false
 
jwt.secret=TuneTix-Secret-Key-2026-MusicBooking!
 
event.service.url=${EVENT_SERVICE_URL:http://localhost:8082}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8084}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8085}
user.service.url=${USER_SERVICE_URL:http://localhost:8081}
 
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html