spring.application.name=payment-service
server.port=8084
 
spring.data.mongodb.uri=mongodb+srv://ViiHAA:viihaa@cluster0.jwkwnsk.mongodb.net/payment_db?retryWrites=true&w=majority&appName=Cluster0
spring.jackson.serialization.write-dates-as-timestamps=false
 
jwt.secret=TuneTix-Secret-Key-2026-MusicBooking!
 
booking.service.url=${BOOKING_SERVICE_URL:http://localhost:8083}
 
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html