server:
  port: 8083

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb+srv://ViiHAA:viihaa@cluster0.jwkwnsk.mongodb.net/payment_db?retryWrites=true&w=majority&appName=Cluster0

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
    user:
      name: admin
      password: password123
