spring.application.name=user-notification-service
server.port=8081

spring.data.mongodb.uri=mongodb+srv://senudissanayake18_db_user:test@user-db.evezku9.mongodb.net/user-db?retryWrites=true&w=majority

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Email Configuration (Gmail SMTP)

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=[YOUR_GMAIL@gmail.com](mailto:YOUR_GMAIL@gmail.com)
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
