spring.application.name=user-notification-service
server.port=8081

spring.data.mongodb.uri=mongodb+srv://senudissanayake18_db_user:test@user-db.evezku9.mongodb.net/user-db?retryWrites=true&w=majority

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

