spring.application.name=event-service
server.port=8082

spring.data.mongodb.uri=mongodb+srv://nisularap_db_user:LqQNSgVtbKfQmqVr@event-db.onnx8fl.mongodb.net/event-db?retryWrites=true&w=majority
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html