spring.application.name=event-service
server.port=8082

spring.data.mongodb.uri=mongodb+srv://nisularap_db_user:LqQNSgVtbKfQmqVr@event-db.onnx8fl.mongodb.net/event-db?retryWrites=true&w=majority
# Fix LocalDate serialization: send "2025-06-15" not [2025,6,15]
spring.jackson.serialization.write-dates-as-timestamps=false
 
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
 